@startuml src
top to bottom direction
hide circle
skinparam classAttributeIconSize 0

package controller {
  class DashboardController {
    +datum: date
    +lade_studium(): Studium
    +lade_kurs_view(kurs_id: string): KursViewModel | None
    +lade_studium_view(): StudiumViewModel
    +erstelle_kurs(name: string, ects: int, schwere: KursSchwere): None
    +aktualisiere_kurs(kurs_id: string, name: string, ects: int, schwere: KursSchwere, noten: float[]): None
    +verschiebe_kurs(kurs_id: string, hoch: bool): None
  }
}

package repo {
  class StudiumRepository {
    +path: Path
    +speichere_studium(studium: Studium): None
    +lade_studium(): Studium | None
  }
}

package domain {
  package service {
    class StudiumPlanungService {
      +setze_kurs_zeitraeume(studium: Studium): None
      +get_semester(studium: Studium): Semester[]
      +get_studium_statistik(studium: Studium, datum: date): StudiumStatistik
      +kurse_fertig(studium: Studium): Kurs[]
      +kurse_offen(studium: Studium, datum: date): Kurs[]
      +kurse_soll(studium: Studium, datum: date): Kurs[]
      +naechste_pruefungen(studium: Studium, datum: date, max_kurse: int): Kurs[]
      +anzahl_ects(studium: Studium): int
      +anzahl_ects_soll(studium: Studium, datum: date): int
      +anzahl_ects_fertig(studium: Studium): int
      +durchschnittsnote(studium: Studium): float | None
      +benoetigte_durchschnittsnote(studium: Studium): float | None
    }
  }

  package entity {
    class Studium {
      +name: str
      +beginn: datetime.date
      +ziel_note: float
      +ziel_monate: int
      +ende(): date
      +anzahl_tage(): int
      +anzahl_kurse(): int
      +vergangene_tage(datum: date): int
      +verbleibende_tage(datum: date): int
      +fuege_kurs_hinzu(kurs_id: str, name: str, ects: int, schwere: KursSchwere, noten: list, beginn: date | None, ende: date | None): None
      +aktualisiere_kurs(kurs_id: str, name: str, ects: int, schwere: KursSchwere, noten: list, beginn: date | None, ende: date | None): None
      +verschiebe_kurs(kurs_id: int, hoch: bool): None
    }
    class Kurs {
      +id: str
      +name: str
      +ects: int
      +noten: float[]
      +beginn: date | None
      +ende: date | None
      +anzahl_tage(): int | None
      +faellig_in_tagen(datum: date): int
      +kann_note_hinzufuegen(): bool
      +ist_fertig(): bool
      +note(): None | float
      +berechne_status(datum: date): KursStatus
      +ist_aktiv(datum: date): bool
      +ist_faellig(datum: date): bool
    }

    class Semester {
      +no: int
      +beginn: date
      +ende: date
      +anzahl_tage(): int
    }

    class StudiumStatistik {
      +anzahl_kurse: int
      +anzahl_kurse_soll: int
      +anzahl_kurse_ist: int
      +anzahl_ects: float
      +anzahl_ects_soll: float
      +anzahl_ects_ist: float
      +durchnitt_note: float
      +benoetigt_note: float
    }

    package enums{
      enum KursSchwere {
        SEHR_LEICHT
        LEICHT
        MITTEL
        SCHWER
        SEHR_SCHWER
      }

      enum KursStatus {
        UNGEPLANT
        OFFEN
        AKTIV
        FAELLIG
        FERTIG
      }
    }
  }
}




package view {
  package transformers {
    class Formatierer {
      +formatiere_note(note: float): str
      +formatiere_datum(datum: date): str
    }

    class StudiumTransformer {
      +transformiere(studium: Studium, statistik: StudiumStatistik, semester_list: Semester[], datum: date): StudiumViewModel
    }

    class KursTransformer {
      +transformiere(kurs: Kurs, datum: date): KursViewModel
    }
    class NotenTransformer {
      +transformiere(ziel_note: float, durchnitt_note: float, benoetigt_note: float): NotenViewModel
    }
    class PruefungTransformer {
      +transformiere_faellige_pruefungen(kurse: Kurs[], datum: date): PruefungViewModel[]
      +transformiere_naechste_pruefungen(kurse: Kurs[], datum: date, max_kurse: int): PruefungViewModel[]
    }
    class StatsTransformer {
      +transformiere(statistik: StudiumStatistik): StatsViewModel
    }
  }

  package models {
    class KursViewModel {
      +id: str
      +name: str
      +schwere: str
      +ects: str
      +anzahl_tage: str
      +hoehe_rel: str
      +beginn: str
      +ende: str
      +ist_fertig: bool
      +ist_faellig: bool
      +ist_aktiv: bool
      +note: str
      +noten: float[]
      +zeige_note2: bool
      +zeige_note3: bool
    }
    class NotenViewModel {
      +ziel: str
      +aktuell: dict[str, str | bool]
      +benoetigt: dict[str, str | bool]
    }
    class PruefungViewModel {
      +name: str
      +faellig_seit_tage: int | None
      +faellig_in_tage: int | None
    }
    class SemesterViewModel {
      +name: str
      +hoehe_rel: int
    }
    class StatsViewModel {
      +anzahl_kurse: int
      +anzahl_ects: float
      +anzahl_kurse_soll: int
      +anzahl_ects_soll: float
      +kurse_ist: dict[str, int | bool]
      +ects_ist: dict[str, float | bool]
    }
    class StudiumViewModel {
      +name: str
      +datum: str
      +anzahl_tage_gesamt: int
      +vergangene_tage: int
      +verbleibende_tage: int
      +faellige_pruefungen: PruefungViewModel[]
      +naechste_pruefungen: PruefungViewModel[]
    }
  }
}

'Controller
DashboardController "1 " o-- "1 " StudiumRepository
DashboardController "1 " o-- "1 " StudiumPlanungService
DashboardController "1 " o-- "1 " StudiumTransformer
DashboardController "1 " --> "1 " Formatierer : erstellt
DashboardController "1 " --> "1 " StudiumViewModel : erstellt
DashboardController "1 " --> "1 " KursViewModel : erstellt
DashboardController "1 " --> "1 " Studium
DashboardController "1 " --> "1 " Studium

'Service
StudiumPlanungService "1 " --> "1 " Studium
StudiumPlanungService "1 " --> "0..* " Kurs
StudiumPlanungService "1 " --> "1..* " Semester
StudiumPlanungService "1 " --> "1 " StudiumStatistik

'Repo
StudiumRepository "1 " --> "1 " Studium
StudiumRepository "1 " --> "0..* " Kurs

'Entity
Studium "1 " *-- "0..* " Kurs
Studium "1 " -- "0..* " KursSchwere
Kurs "1 " o-- "1 " KursSchwere
Kurs "1 " o-- "1 " KursStatus

'View
StudiumTransformer "1 " o-- "1 " KursTransformer
StudiumTransformer "1 " o-- "1 " StatsTransformer
StudiumTransformer "1 " o-- "1 " NotenTransformer
StudiumTransformer "1 " o-- "1 " PruefungTransformer
StudiumTransformer "1 " --> "1 " Studium : transformiert
StudiumTransformer "1 " --> "1 " Semester : transformiert
StudiumTransformer "1 " --> "1 " StudiumStatistik : transformiert
StudiumTransformer "1 " --> "1 " Formatierer
StudiumTransformer "1 " --> "1 " StudiumViewModel : erstellt
StudiumTransformer "1 " --> "1 " SemesterViewModel : erstellt

KursTransformer "1 " o-- "1 " Formatierer
KursTransformer "1 " --> "1 " Kurs : transformiert
KursTransformer "1 " --> "1 " KursViewModel : erstellt

NotenTransformer "1 " o-- "1 " Formatierer

PruefungTransformer "1 " --> "0..* " Kurs : transformiert
PruefungTransformer "1 " --> "0..* " PruefungViewModel : erstellt

StatsTransformer "1 " --> "1 " StudiumStatistik : transformiert
StatsTransformer "1 " --> "1 " StatsViewModel : erstellt

StudiumViewModel "1 " o-- "0..* " KursViewModel
StudiumViewModel "1 " o-- "1..* " SemesterViewModel
StudiumViewModel "1 " o-- "0..* " PruefungViewModel
StudiumViewModel "1 " o-- "1 " NotenViewModel
StudiumViewModel "1 " o-- "1 " StatsViewModel



'layout
controller -[hidden]d->domain
domain -[hidden]d->view

transformers -[hidden]d-> models
StudiumTransformer -[hidden]d-> KursTransformer
KursTransformer -[hidden]d-> NotenTransformer
NotenTransformer -[hidden]d-> PruefungTransformer
PruefungTransformer -[hidden]d-> StatsTransformer
StatsTransformer -[hidden]d-> Formatierer

StudiumViewModel -[hidden]d-> KursViewModel
KursViewModel -[hidden]d-> NotenViewModel
NotenViewModel -[hidden]d-> PruefungViewModel
PruefungViewModel -[hidden]d-> StatsViewModel


@enduml
